name: marvel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  get_it: ^7.7.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  simple_connection_checker: ^0.2.1
  crypto: ^3.0.3
  get: ^4.6.6
  cached_network_image: ^3.3.1
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: Light
      fonts:
        - asset: assets/fonts/light.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/regular.ttf
    
    - family: Bold
      fonts:
        - asset: assets/fonts/bold.ttf
  
