// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb26TA0OqA-ZIRM-uh_MtLSrAdPYssHgk',
    appId: '1:270007489345:web:4c83fcd6de4a7235b887c0',
    messagingSenderId: '270007489345',
    projectId: 'mottu-app',
    authDomain: 'mottu-app.firebaseapp.com',
    storageBucket: 'mottu-app.appspot.com',
    measurementId: 'G-ZDCKXHCL58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJVsxGOWMhdjr7RpQFDJQHWNZ3t54mKU',
    appId: '1:270007489345:android:63f984699207ba92b887c0',
    messagingSenderId: '270007489345',
    projectId: 'mottu-app',
    storageBucket: 'mottu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwHaxdwa1xXZuTIeI7dUODXAwpu4MvOZM',
    appId: '1:270007489345:ios:03a479e9fc50ad41b887c0',
    messagingSenderId: '270007489345',
    projectId: 'mottu-app',
    storageBucket: 'mottu-app.appspot.com',
    iosBundleId: 'com.mottu.marvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwHaxdwa1xXZuTIeI7dUODXAwpu4MvOZM',
    appId: '1:270007489345:ios:03a479e9fc50ad41b887c0',
    messagingSenderId: '270007489345',
    projectId: 'mottu-app',
    storageBucket: 'mottu-app.appspot.com',
    iosBundleId: 'com.mottu.marvel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb26TA0OqA-ZIRM-uh_MtLSrAdPYssHgk',
    appId: '1:270007489345:web:db300bf215e2f57eb887c0',
    messagingSenderId: '270007489345',
    projectId: 'mottu-app',
    authDomain: 'mottu-app.firebaseapp.com',
    storageBucket: 'mottu-app.appspot.com',
    measurementId: 'G-E46Q6BE5FG',
  );
}
